//! Long-running watcher that organizes the input folder as papers arrive.
//!
//! The watcher treats filesystem events as a wake-up hint only: the input
//! folder scan is the single source of truth for what needs organizing. That
//! keeps the loop correct when events are coalesced, missed, or generated by
//! the watcher's own file moves.

use std::{
    collections::BTreeMap,
    path::{Path, PathBuf},
    time::Duration,
};

use notify::{Event, RecommendedWatcher, RecursiveMode, Watcher};
use tokio::sync::mpsc::{self, UnboundedReceiver, error::TryRecvError};

use crate::{
    config,
    config::AppConfig,
    error::{AppError, Result},
    inputs::RunOverrides,
    papers::discovery::discover_pdf_candidates,
    terminal::{self, Verbosity},
};

use super::{
    path_resolution::{absolutize, absolutize_config},
    run::run,
};

/// How long the input folder must stay unchanged before a run starts, so that
/// PDFs still being copied in are not organized half-written.
const SETTLE: Duration = Duration::from_secs(3);

/// Rescan interval used when no filesystem event arrives, so a missed event
/// delays a run rather than stalling the watcher.
const IDLE_RESCAN: Duration = Duration::from_secs(60);

/// PDFs waiting in the input folder, by path and current size.
///
/// Comparing two snapshots answers both watcher questions: has the folder
/// settled, and has anything changed since the last run.
type InputSnapshot = BTreeMap<PathBuf, u64>;

/// Resolves CLI arguments into an application config and watches the input
/// folder until interrupted.
///
/// # Errors
/// Returns an error when config resolution fails or the watcher cannot be
/// installed on the input folder.
pub async fn watch_with_args(overrides: RunOverrides) -> Result<()> {
    watch(resolve_watch_config(overrides)?).await
}

/// Writes a starter config into `input`, defaulting to the current directory,
/// and returns its path.
///
/// Unlike watching, this ignores the configured input folder: the folder being
/// set up is the one named on the command line, or the one the user is
/// standing in.
///
/// # Errors
/// Returns an error when the folder is missing, or a config already exists
/// there and `force` is not set.
pub fn init_watch_config(
    input: Option<PathBuf>,
    output: Option<PathBuf>,
    force: bool,
) -> Result<PathBuf> {
    let folder = absolutize(input.as_deref().unwrap_or(Path::new(".")))?;
    let output = output.map(|output| absolutize(&output)).transpose()?;
    config::init_watch_config(&folder, output.as_deref(), force)
}

/// Resolves the config for watching, layering the watched folder's own
/// `syp.toml` over the XDG config.
///
/// The folder is settled first from the other sources, because the folder
/// config lives inside the folder it configures.
fn resolve_watch_config(overrides: RunOverrides) -> Result<AppConfig> {
    let folder = watch_folder(&config::resolve_config(overrides.clone())?)?;
    config::resolve_config_for_folder(overrides, &folder)
}

fn watch_folder(config: &AppConfig) -> Result<PathBuf> {
    absolutize(&config.input)
}

/// Organizes the input folder whenever new PDFs settle in it.
///
/// Runs until the process is interrupted. A failed run is reported and the
/// watcher keeps going, but the same unchanged input is not retried: the files
/// stay put until they change or a new PDF arrives.
///
/// # Errors
/// Returns an error when the input folder is missing or cannot be watched.
pub async fn watch(config: AppConfig) -> Result<()> {
    let config = absolutize_config(config)?;
    let verbosity = Verbosity::new(config.verbose, config.debug, config.quiet);

    if !config.input.is_dir() {
        return Err(AppError::Validation(format!(
            "watch input folder does not exist: {}",
            config.input.display()
        )));
    }

    // Runs happen without anyone at the keyboard, so taxonomy review prompts
    // must resolve to their defaults instead of blocking the loop.
    let _backend = terminal::install_unattended_backend();

    let folder_config = config::watch_config_path(&config.input);
    if folder_config.is_file() {
        watch_line(
            verbosity,
            format!(
                "using {}",
                verbosity.accent(folder_config.display().to_string())
            ),
        );
    }

    let (_watcher, mut events) = watch_input(&config)?;
    watch_line(
        verbosity,
        format!(
            "watching {} -> {} ({})",
            verbosity.accent(config.input.display().to_string()),
            verbosity.accent(config.output.display().to_string()),
            if config.dry_run {
                "preview only; pass --apply to move files"
            } else {
                "apply mode"
            }
        ),
    );

    let mut last_run: Option<InputSnapshot> = None;
    loop {
        let pending = pending_input(&config)?;
        if pending.is_empty() || last_run.as_ref() == Some(&pending) {
            if !wait_for_change(&mut events).await {
                return Ok(());
            }
            continue;
        }

        tokio::time::sleep(SETTLE).await;
        if pending_input(&config)? != pending {
            continue;
        }

        drain(&mut events);
        watch_line(
            verbosity,
            format!("organizing {} pending PDF(s)", pending.len()),
        );
        last_run = Some(pending);

        match run(config.clone()).await {
            Ok(report) => watch_line(
                verbosity,
                format!(
                    "organized {} paper(s), {} planned action(s)",
                    report.processed,
                    report.actions.len()
                ),
            ),
            Err(err) => verbosity.error_line(
                "WATCH",
                format!("run failed: {err}; waiting for the next change"),
            ),
        }
    }
}

/// Reports watcher lifecycle progress, which stays visible without `--verbose`
/// because it is the only feedback an unattended run gives.
fn watch_line(verbosity: Verbosity, message: String) {
    verbosity.info(format!("{} {message}", verbosity.accent("WATCH")));
}

fn pending_input(config: &AppConfig) -> Result<InputSnapshot> {
    input_snapshot(&config.input, &config.output, config.recursive)
}

/// PDFs currently waiting in the input folder.
///
/// Anything already inside the output folder is excluded, so a library nested
/// under the input folder is never re-ingested.
fn input_snapshot(input: &Path, output: &Path, recursive: bool) -> Result<InputSnapshot> {
    let candidates = discover_pdf_candidates(input, recursive)?;
    Ok(candidates
        .into_iter()
        .filter(|candidate| !candidate.path.starts_with(output))
        .map(|candidate| (candidate.path, candidate.size_bytes))
        .collect())
}

fn watch_input(config: &AppConfig) -> Result<(RecommendedWatcher, UnboundedReceiver<Event>)> {
    let (sender, receiver) = mpsc::unbounded_channel();
    let mut watcher = notify::recommended_watcher(move |event: notify::Result<Event>| {
        if let Ok(event) = event {
            let _ = sender.send(event);
        }
    })
    .map_err(watch_error)?;

    let mode = if config.recursive {
        RecursiveMode::Recursive
    } else {
        RecursiveMode::NonRecursive
    };
    watcher.watch(&config.input, mode).map_err(watch_error)?;
    Ok((watcher, receiver))
}

/// Waits for the next filesystem event, giving up after [`IDLE_RESCAN`] so the
/// caller rescans anyway.
///
/// Returns `false` once the watcher is gone and no more events can arrive.
async fn wait_for_change(events: &mut UnboundedReceiver<Event>) -> bool {
    match tokio::time::timeout(IDLE_RESCAN, events.recv()).await {
        Ok(Some(_)) => true,
        Ok(None) => false,
        Err(_) => true,
    }
}

/// Discards events already queued, including the ones a run just caused.
fn drain(events: &mut UnboundedReceiver<Event>) {
    while !matches!(
        events.try_recv(),
        Err(TryRecvError::Empty | TryRecvError::Disconnected)
    ) {}
}

fn watch_error(err: notify::Error) -> AppError {
    AppError::Execution(format!("filesystem watch error: {err}"))
}

#[cfg(test)]
mod tests {
    use std::fs;

    use tempfile::tempdir;

    use super::input_snapshot;

    #[test]
    fn input_snapshot_skips_pdfs_already_in_the_output_library() {
        let temp = tempdir().expect("tempdir");
        let input = temp.path();
        let output = input.join("sorted");
        fs::create_dir_all(output.join("ml")).expect("create output tree");
        fs::write(input.join("new.pdf"), b"%PDF-1.4 new").expect("write pending pdf");
        fs::write(output.join("ml/filed.pdf"), b"%PDF-1.4 filed").expect("write filed pdf");

        let snapshot = input_snapshot(input, &output, true).expect("snapshot");

        assert_eq!(
            snapshot.keys().collect::<Vec<_>>(),
            vec![&input.join("new.pdf")]
        );
    }

    #[test]
    fn input_snapshot_changes_while_a_pdf_is_still_being_written() {
        let temp = tempdir().expect("tempdir");
        let input = temp.path();
        let output = input.join("sorted");
        fs::write(input.join("partial.pdf"), b"%PDF-1.4").expect("write first chunk");

        let first = input_snapshot(input, &output, true).expect("first snapshot");
        fs::write(input.join("partial.pdf"), b"%PDF-1.4 and the rest").expect("write rest");
        let second = input_snapshot(input, &output, true).expect("second snapshot");

        assert_ne!(first, second);
    }
}
