use std::{
    fs,
    path::{Path, PathBuf},
};

use directories::BaseDirs;
use serde::{Deserialize, Serialize};

use crate::{error::Result, tui::theme::UiThemeName};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub(crate) struct TuiPreferences {
    #[serde(default)]
    pub(crate) theme: UiThemeName,
}

impl Default for TuiPreferences {
    fn default() -> Self {
        Self {
            theme: UiThemeName::default(),
        }
    }
}

pub(crate) fn load_tui_preferences() -> Result<TuiPreferences> {
    let Some(path) = xdg_tui_preferences_path() else {
        return Ok(TuiPreferences::default());
    };

    load_tui_preferences_from_path(&path)
}

pub(crate) fn save_tui_preferences(prefs: &TuiPreferences) -> Result<PathBuf> {
    let Some(path) = xdg_tui_preferences_path() else {
        return Err(crate::error::AppError::Config(
            "could not resolve XDG config directory".to_string(),
        ));
    };

    write_tui_preferences_at(&path, prefs)?;
    Ok(path)
}

fn xdg_tui_preferences_path() -> Option<PathBuf> {
    BaseDirs::new().map(|base| base.config_dir().join("sortyourpapers").join("tui.toml"))
}

fn load_tui_preferences_from_path(path: &Path) -> Result<TuiPreferences> {
    if !path.exists() {
        return Ok(TuiPreferences::default());
    }

    let raw = fs::read_to_string(path)?;
    Ok(toml::from_str::<TuiPreferences>(&raw).unwrap_or_default())
}

fn write_tui_preferences_at(path: &Path, prefs: &TuiPreferences) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }

    let serialized = toml::to_string(prefs).map_err(|err| {
        crate::error::AppError::Config(format!("failed to serialize tui prefs: {err}"))
    })?;
    fs::write(
        path,
        format!(
            "# SortYourPapers TUI preferences\n# Generated by the TUI theme switch\n\n{serialized}"
        ),
    )?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::fs;

    use tempfile::tempdir;

    use super::{TuiPreferences, load_tui_preferences_from_path, write_tui_preferences_at};
    use crate::tui::theme::UiThemeName;

    #[test]
    fn missing_preferences_default_to_dark_theme() {
        let dir = tempdir().expect("tempdir");
        let path = dir.path().join("tui.toml");

        let loaded = load_tui_preferences_from_path(&path).expect("load prefs");

        assert_eq!(loaded.theme, UiThemeName::Dark);
    }

    #[test]
    fn preferences_round_trip_light_theme() {
        let dir = tempdir().expect("tempdir");
        let path = dir.path().join("tui.toml");
        let prefs = TuiPreferences {
            theme: UiThemeName::Light,
        };

        write_tui_preferences_at(&path, &prefs).expect("write prefs");
        let loaded = load_tui_preferences_from_path(&path).expect("load prefs");

        assert_eq!(loaded, prefs);
    }

    #[test]
    fn invalid_preferences_fall_back_to_dark_theme() {
        let dir = tempdir().expect("tempdir");
        let path = dir.path().join("tui.toml");
        fs::write(&path, "theme = \"nope\"\n").expect("write invalid prefs");

        let loaded = load_tui_preferences_from_path(&path).expect("load prefs");

        assert_eq!(loaded.theme, UiThemeName::Dark);
    }
}
