[package]
name = "syp-ai"
version.workspace = true
edition.workspace = true

[dependencies]
base64.workspace = true
async-trait.workspace = true
clap.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
genai = "0.6.5"

